[Add] Topbar, Homepage
binh-nguyen49-jh/react_training pull request #3
Opened 2022-05-04 10:56 UTC by binh-nguyen49-jh

2022-05-05 03:41 UTC, anh-dinh-jh requested changes

2022-05-05 03:41 UTC, anh-dinh-jh commented on .vscode/settings.json
> +}
Should ignore this file when pushing new commits

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/API/authentication.js
>  };
Is there any solution to make this function a promise instead of returning a new promise?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/API/authentication.js
>      }
Same as above

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/API/authentication.js
> +      const userProfile = UserAPI.getUser(user.uid);
Does this one need `await`?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/API/postAPI.js
> +    const image_urls = await Promise.all(
Should use `camelCase` to name a variable

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/API/postAPI.js
> +    delete post['images'];
Is there any solution that we don't need to use `delete` but using object destructuring ?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/API/postAPI.js
> +    );
Should put the whole logic into another function instead to make the context clear

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/App.test.js
> +*/
Should eliminate commented code

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Avatar/Avatar.jsx
> +      ...style,
Should use CSS classes instead of inline-style

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/Form.jsx
> +    console.log(isValidForm);
Please remove `console.log`, it's a bad practice

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/Form.jsx
> +    let isValidForm = this.checkValidateForm(false);
Is `isValidForm` changed later? Why do we have to use `let`?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/Form.jsx
> +    newForm[field].error = errorMessage;
Is there any better way to declare this `newForm` using object destructuring?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/Form.jsx
> +  checkValidateForm = (updateErrors = true) => {
Is this default value `true` redudant? Because the `updateError` above is always true if there is no `updateErrors` param in this func

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/Form.jsx
> +      }
Why don't we break the loop instead of waiting for the loop to finish?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/Form.jsx
> +            formError: error.code.split('/')[1].split('-').join(' '),
Please declare a function in `utils` to process the complex operations to increase readability

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/Form.jsx
> +            formError: error.code.split('/')[1].split('-').join(' '),
Is there a way to shorten this logic?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/LoginForm.jsx
> +    return logInWithEmail(this.state.email.value, this.state.password.value);
Please use object destructuring to avoid the duplication of `this.state`

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Forms/LoginForm.jsx
> +          />
Please declare all required states from `this.state` to avoid calling it multiple times

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/HOC/Modal.jsx
> +        }}
Please don't use inline-style but CSS classes

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/HOC/Popover.jsx
> +        }}
Same as above

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/HOC/ProtectedRoute.jsx
> +  }
Can we shorten this logic to 1 or 2 lines?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/HOC/withRouter.js
> +    }
Be careful with the formatting

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Header/Header.jsx
> +              </Link>
Should create a separate component for the logo to reuse

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Header/Header.jsx
> +                        'https://res.cloudinary.com/daten/image/upload/v1650819174/avatar_mlwjsm.jpg'
This link should be defined as a constant to easily understand what it is about

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Header/Header.jsx
> +                  </Link>
Why don't we create a `NavItem` component?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Badge.jsx
> +      }}>
Same as the above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Comments.jsx
> +        {showingComment ? 'Ẩn tất cả bình luận' : 'Xem tất cả bình luận'}
Should use the same language for all pages

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/HiddenPost.jsx
> +              backgroundColor: 'var(--gray-2-cl)',
Same as above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/HiddenPost.jsx
> +          </svg>
Should create a separate component for this

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.jsx
> +    console.log(commentRef.current.value);
Please remove console.log

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.jsx
> +              )}
Should not process the complex logic inside JSX

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.jsx
> +          </svg>
Same as above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.jsx
> +              </svg>
Same as the above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.jsx
> +          </p>
What if the result of this condition is `falsy` value?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.scss
> +          fill: #000;
Please declare name for this color

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.scss
> +          fill: #949494;
Same as the comment above

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/Post.scss
> +      fill: #ffffff;
Same as the comment above

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/PostCarousel.jsx
> +        }}>
Same as the above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/PostCarousel.jsx
> +          </svg>
Please fix all

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/RoleIcon.jsx
> +        }}>
Same as the comment above

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/Post/UserPopover.jsx
> +            }}>
Same as the comment above

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/PostForm/PostForm.jsx
> +      let missingImageUrl = photoUrls.findIndex((url) => url == null);
Please rename this variable as it's confusing

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/PostForm/PostForm.jsx
> +            }}
Same as the above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/PostForm/PostForm.scss
> +  background-color: #fafafa;
Should declare a name for this color

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/PostList/PostList.jsx
> +        ...newPosts.sort((a, b) => b.createdAt.seconds - a.createdAt.seconds),
Why don't we order while querying posts?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/PostList/PostList.jsx
> +        }}>
Same as above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/components/TextAreaField/TextAreaField.jsx
> +        </svg>
Same as above comment

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/hooks/authentication.jsx
> +      console.log('update profile: ', userProfile);
Should remove `console.log`

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/hooks/authentication.jsx
> +      }
Can we shorten this logic?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/index.css
> +  --emoji-btn-bg: var(--primary-cl);
To avoid duplication, simply write the correct color name for all duplicated hex codes (e.g. #ffffff)

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/utils/debounce.js
> +export default function debounced(func, wait) {
Is it the correct name?

2022-05-05 03:41 UTC, anh-dinh-jh commented on src/utils/formValidate.js
> +  value && !/^\w+([._-]?\w+)*@\w+([._-]?\w+)*([.]\w{2,3})+$/i.test(value)
Should put the whole regex into a constant

2022-05-09 00:26 UTC, anh-dinh-jh requested changes

2022-05-09 00:26 UTC, anh-dinh-jh commented on src/API/authentication.js
> +    uid: res.user.uid,
We already had `user` above, why do we have to call `res.user` again? Also, if the param of `createUser` and the result of this func is same, please combine those two

2022-05-09 00:26 UTC, anh-dinh-jh commented on src/components/Forms/LoginForm.jsx
> +            disabled={!isSubmittable}
Should rename the variable to make it match the context

2022-05-09 00:26 UTC, anh-dinh-jh commented on src/API/postAPI.js
> +    );
Do you consider combine this logic as well because at this step, docs is absolutely an array that has values

2022-05-09 00:26 UTC, anh-dinh-jh commented on src/API/userAPI.js
> +      position: [...position.split(',')],
The destructuring operation is redundant

2022-05-09 00:26 UTC, anh-dinh-jh commented on src/utils/uploadImage.js
> +  });
Can we use async await for this one?

2022-05-09 02:18 UTC, binh-nguyen49-jh commented on src/utils/uploadImage.js
> +  });
No, we can't. I can only refactor this part using async/await
![image](https://user-images.githubusercontent.com/101536791/167329230-359322df-4959-4350-9348-c199f289cdaf.png)

2022-05-09 02:48 UTC, anh-dinh-jh commented on .vscode/settings.json
> +}
Please remove this file as well

2022-05-09 02:53 UTC, anh-dinh-jh commented on src/API/authentication.js
> +  UserNotFound: 'User not found',
Should be all caps

2022-05-09 02:53 UTC, anh-dinh-jh commented on src/API/postAPI.js
> +        );
Can we shorten this logic?

2022-05-09 02:54 UTC, anh-dinh-jh commented on src/API/userPostAPI.js
> +    return userPostDoc.docs[0].data();
Can we shorten this logic?

2022-05-11 05:12 UTC, merged